/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.zip;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @DisplayName(" TWO LINKED LIST EQEL IN LENGTH")
    @Test void testZipEqals() {
        linkedList<String> newNode1=new linkedList();
        linkedList<String> newNode2=new linkedList();


        newNode1.add("3");
        newNode1.add("1");
        newNode1.add("7");


        newNode2.add("a");
        newNode2.add("b");
        newNode2.add("c");


        assertEquals(linkedList.zip(newNode1,newNode2).toString(),"7=>c=>1=>b=>3=>a=>null");

    }

    @DisplayName(" One longer")
    @Test void testOneLonger() {
        linkedList<String> newNode1=new linkedList();
        linkedList<String> newNode2=new linkedList();


        newNode1.add("3");
        newNode1.add("1");
        newNode1.add("7");


        newNode2.add("a");
        newNode2.add("b");



        assertEquals(linkedList.zip(newNode1,newNode2).toString(),"7=>b=>1=>a=>3=>null");

    }

    @DisplayName(" Two longer")
    @Test void testTwoLonger() {
        linkedList<String> newNode1=new linkedList();
        linkedList<String> newNode2=new linkedList();


        newNode1.add("3");
        newNode1.add("1");



        newNode2.add("a");
        newNode2.add("b");
        newNode2.add("c");
        newNode2.add("d");

        assertEquals(linkedList.zip(newNode1,newNode2).toString(),"1=>d=>3=>c=>b=>a=>null");

    }


    @DisplayName(" ONE NULL")
    @Test void testOneNull() {
        linkedList<String> newNode1=new linkedList();
        linkedList<String> newNode2=new linkedList();

        newNode2.add("a");
        newNode2.add("b");
        newNode2.add("c");
        newNode2.add("d");

        assertEquals(linkedList.zip(newNode1,newNode2).toString(),"d=>c=>b=>a=>null");

    }
}
