/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.breadth.first;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
@DisplayName("TEST")
    @Test void test() {
    int[][] arr={{0,1,0,0,1},
            {1,0,1,1, 0},
            {0, 1, 0, 1, 0},
            {0  ,1  ,1  ,0  ,1},
            {  1,  0,  0,  1,  0}};
    App.represintaion(arr);
    assertEquals(  App.represintaion(arr),"a|->b->e\n" +
            "b|->a->c->d\n" +
            "c|->b->d\n" +
            "d|->b->c->e\n" +
            "e|->a->d\n");

    }
}
