/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

Node newNode=new Node("wael");
       Node newNode2=new Node("yazan");
       Node newNode3=new Node("ahamd");
       Queue QQ=new Queue();
       QQ.enqueue(newNode);
       QQ.enqueue(newNode2);
       QQ.enqueue(newNode3);
       System.out.println(QQ.toString());
       QQ.dequeue();
       System.out.println(QQ.toString());
    }
}
