/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Navigator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void test2() {
        Navigator nav2 = new Navigator();

        nav2.go("1");
        nav2.go("2");

        assertEquals("1", nav2.back());
        nav2.go("3");
        assertEquals("1", nav2.back());
    }

    @Test
    void test1() {
        Navigator nav = new Navigator();
        // link(1), link(2), link(3), back()
        nav.go("1");
        nav.go("2");
        nav.go("3");
        assertEquals("2", nav.back());
    }

    @Test
    void test3() {
        Navigator nav3=new Navigator();

        nav3.go("1");
        nav3.go("2");
        nav3.go("3");
        nav3.go("4");
        assertEquals("3",nav3.back());
        assertEquals("4",nav3.forward());

        nav3.go("5");
        assertEquals("4",nav3.back());

    }

}
