/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ReciprocalFactorial;

import org.junit.jupiter.api.Test;


import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        BigDecimal expected = BigDecimal.valueOf(0.718281828459054);
        assertEquals(classUnderTest.ReciprocalFactorial(20),expected );
    }
}
