/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package illegalCharacter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test1() {

     assertEquals(App.Sanitizer("http://code.org/hour of code.html"),"http://code.org/hour%20of%20code.html");
    }
    @Test void test2() {
        assertEquals(App.Sanitizer("ht ml "),"ht%20ml%20");

    }
    @Test void test3() {
        assertEquals(App.Sanitizer("www.ui.com/ wael qawasmi "),"www.ui.com/%20wael%20qawasmi%20");

    }
}
