/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test1() {
        App classUnderTest = new App();
        int arr1[] = {8, 4, 23, 42, 16, 15};
        int reselt1[]={4, 8, 15, 16, 23, 42};
        classUnderTest.Mergesort(arr1);
        assertArrayEquals(arr1, reselt1);
    }

    @Test void test2() {
        App classUnderTest = new App();
        int arr2[] = {20,18,12,8,5,-2};
        int reselt2[]={-2, 5, 8, 12, 18, 20};
        classUnderTest.Mergesort(arr2);
        assertArrayEquals(arr2, reselt2);
    }

    @Test void test3() {
        App classUnderTest = new App();
        int arr2[] = {5,12,7,5,5,7};
        int reselt2[]={5, 5, 5, 7, 7, 12};
        classUnderTest.Mergesort(arr2);
        assertArrayEquals(arr2, reselt2);
    }

    @Test void test4() {
        App classUnderTest = new App();
        int arr2[] = {2,3,5,7,13,11};
        int reselt2[]={2, 3, 5, 7, 11, 13};
        classUnderTest.Mergesort(arr2);
        assertArrayEquals(arr2, reselt2);
    }
}
