/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commonWord;

import java.util.Collections;
import java.util.HashMap;
import java.util.Locale;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(   commonWord("No. Try not. Do or do not. There is no try."));

}



    public  static  String commonWord (String the) {
        HashMap<String, Integer> hashMap = new HashMap();


        the = the.toLowerCase(Locale.ROOT).replace('.', ' ');
        the = the.replace("  ", " ");
        String[] arr = the.split(" ");
        for (String word : arr) {
            hashMap.computeIfPresent(word, (k, v) -> v + 1);
            hashMap.computeIfAbsent(word, (v) -> 1);
        }

        int max = Collections.max(hashMap.values());

        for (String k : hashMap.keySet()) {
            if (max == hashMap.get(k)) {
                return k;
            }

        }
        return null;
    }
}
