/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MostRepeatDigit;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int []test={25,58,78,25,55,22};
        System.out.println(Arrays.toString(solution(test)));
    }


    public  static int[] solution(int[] a) {

        HashMap<String,Integer> CountDigit= new HashMap<String,Integer>();

        for(int i=0;i<10;i++)
            CountDigit.put(String.valueOf(i),0);// to stor all digit in hashap

        for(int num:a){
            String[] NUm=String.valueOf(num).split(""); // to sprate the digits and stor it
            for (String i : NUm) {
                CountDigit.put(i,CountDigit.get(i)+1); // to put the count of digit

            }
        }
        Integer maxumRepeted= Collections.max(CountDigit.values()); // tp get the maxiemam repeted
        ArrayList <Integer> maxumRepetedDigit=new ArrayList<Integer>(); // to stor the max rpeted digit

        for(String count:CountDigit.keySet()){
            if(maxumRepeted==CountDigit.get(count)){
                maxumRepetedDigit.add(Integer.parseInt(count));
            }
        }
        int []b=maxumRepetedDigit.stream().mapToInt(Integer::intValue).toArray();  // to convert  array

        return b;


    }

}
