/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BFS;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {


    public static void main(String[] args) {
        Map<Integer,List<Integer>>GraphList=new HashMap<Integer,List<Integer>>();
        List<Integer>adj0=new ArrayList<>();
        adj0.add(1);
        adj0.add(4);

        List<Integer>adj1=new ArrayList<>();
        adj1.add(0);


        List<Integer>adj4=new ArrayList<>();
        adj4.add(1);





        GraphList.putIfAbsent(1,adj1);
        GraphList.putIfAbsent(0,adj0);
        GraphList.putIfAbsent(4,adj4);

       System.out.println( Graph.checkBathDestination(0,4,GraphList));

    }
}
