/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Integer [] arr={8,4,23,42,16,15};
        List<Integer> list1 = new ArrayList<Integer>();
        Collections.addAll(list1, InsertionSort(arr));
        System.out.println( list1);
     ;


    }

    public static Integer[]   InsertionSort(Integer[] arr)
    {

        for (int i = 0; i < arr.length ; i++) {
            int j = i - 1;
            int temp = arr[i];
            List<Integer> list1 = new ArrayList<Integer>();
            Collections.addAll(list1, arr);
            while (j>=0 && arr[j] > temp){
                arr[j + 1] = arr[j];
                j=j - 1;
               // System.out.println("j>=0 && arr[j]= true");
              //  Collections.addAll(list1, arr);
             //   System.out.println("|"+i+"|true"+"|"+list1+"|"+j+"|");
               // System.out.println("j="+j+"\t arr[j + 1]="+arr[ j+1]+"   temp ="+temp +"\t");
                }

                arr[j + 1] = temp ;

            //System.out.println("|"+i+"|false"+"|"+list1+"|"+j+"|");
        }
        return arr;

        }

    }

