/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Navigator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
   Navigator nav=new Navigator();
       // link(1), link(2), link(3), back()
   nav.go("1");
   nav.go("2");
   nav.go("3");
 System.out.println(nav.back());

      //  link(1), link(2), back(), link(3), back();
        Navigator nav2=new Navigator();

        nav2.go("1");
        nav2.go("2");
        System.out.print(nav2.back()+",");
        nav2.go("3");
        System.out.println(nav2.back());

        //link(1), link(2), link(3), link(4), back(), forward(), link(5), back()
        Navigator nav3=new Navigator();

        nav3.go("1");
        nav3.go("2");
        nav3.go("3");
        nav3.go("4");
        System.out.print(nav3.back()+",");
        System.out.print(nav3.forward()+",");
        nav3.go("5");
        System.out.print(nav3.back());
    }
}
