/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeatedWord;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void test1() {
        App classUnderTest = new App();
        String text1 = "Once upon a time, there was a brave princess who...";
        assertEquals(App.repeatedWord(text1), "a");
    }
    @Test
    void test2() {
        String text2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        assertEquals(App.repeatedWord(text2), "it");
    }
    @Test
    void test3() {
        String text3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        assertEquals(App.repeatedWord(text3), "summer");

    }
}
