/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

public class Library {
    public static void main(String[] args) {

            animal ca1=new animal("cat");
        animal ca2=new cat("cat");
        animal ca3=new cat("cat");
        animal d1 =new dog("dog");
        animal d2 =new dog("dog");
        animal d3 =new dog("dog");
        AnimalShelter shalter= new AnimalShelter();
        shalter.enqueue(ca1);
        shalter.enqueue(ca2);
        shalter.enqueue(ca3);
        shalter.enqueue(d1);
        shalter.enqueue(d2);
        shalter.enqueue(d3);
       System.out.println(shalter.toString());
    }
}


