/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.insertions;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        linkedList<String>Node=new linkedList<>();
        Node.append("terorest");
        Node.addFirst("alaa");
        Node.append("ho");
     Node.addFirst("wael");
        Node.addFirst("ahmad");
        Node.insertAfter("alaa","yaser");

        Node.insertBefor("ahmad","ddddddddd");
Node.printAll();

    }
}
