/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeftJoin;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import static LeftJoin.App.leftJoin;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void test() {



        HashMap<String,String> hash1= new HashMap<String,String>();
        hash1.put("wael","waed");
        hash1.put("khallel","yazan");
        hash1.put("ali","omar");
        hash1.put("majed","hazim");




        HashMap<String,String> hash2= new HashMap<String,String>();
        //  hash1.put("wael","waed");
        hash2.put("khallel","1");
        hash2.put("I","omar");
        hash2.put("majed","2");
        System.out.println(leftJoin(hash1,hash2));
 String [][] arr= {{"wael", "ward", null}, {"khallel", "yazan", "1"}, {"majed", "hazim", "2"}, {"ali", "omar", null}};


        assertArrayEquals(App.leftJoin(hash1,hash2).toArray(),arr);


    }
}
