/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.max;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        BinaryTree binaryTree=new BinaryTree();

        binaryTree.setRoot(new BTNode(110999));

        binaryTree.getRoot().setLeft(new BTNode(200));

        binaryTree.getRoot().setRight(new BTNode(10));
        binaryTree.getRoot().setRight(new BTNode(1000));

        System.out.println("......................"+binaryTree.treeMax( binaryTree.getRoot()));


    }
}
