/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.zip;

import java.util.List;

public class App {


    public static void main(String[] args) {
        linkedList<String> newNode1=new linkedList();
        linkedList<String> newNode2=new linkedList();


        newNode1.add("3");
        newNode1.add("1");
        newNode1.add("7");
        newNode1.add("9");
        newNode1.add("10");
//        newNode2.add("4");
//        newNode2.add("9");


//
//
       newNode1.printAll();
       newNode1.reverse();
        newNode1.printAll();
//        newNode2.printAll();
//        System.out.println( "LP");
//    linkedList.zip(newNode1,newNode2).printAll();
      //  System.out.println( "size"+newNode1.size);
    }
}
