/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.max;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        BinaryTree binaryTree=new BinaryTree();

        binaryTree.setRoot(new BTNode(2));

        binaryTree.getRoot().setLeft(new BTNode(7));

        binaryTree.getRoot().setRight(new BTNode(5));
        binaryTree.getRoot().getRight().setRight(new BTNode(9));
        binaryTree.getRoot().getRight().getRight().setLeft(new BTNode(4));
        binaryTree.getRoot().getLeft().setLeft(new BTNode(2));
        binaryTree.getRoot().getLeft().setRight(new BTNode(6));
        binaryTree.getRoot().getLeft().getLeft().setRight(new BTNode(11));
        binaryTree.getRoot().getLeft().getLeft().setLeft(new BTNode(5));
        System.out.println("......................"+binaryTree.treeMax( binaryTree.getRoot()));

     assertEquals(binaryTree.treeMax( binaryTree.getRoot()),11);
    }
}
