/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.breadth.first;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
@DisplayName("TEST1")
    @Test void test1() {
        Graph graph=new Graph();
        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");
        graph.addNode("Naboo");

    graph.addEdge(new Vertex("Pandora"),new Vertex("Arendelle"));
    graph.addEdge(new Vertex("Metroville"),new Vertex("Arendelle"));
    graph.addEdge(new Vertex("Monstroplolis"),new Vertex("Arendelle"));
    graph.addEdge(new Vertex("Monstroplolis"),new Vertex("Metroville"));
    graph.addEdge(new Vertex("Metroville"),new Vertex("Narnia"));

    graph.addEdge(new Vertex("Naboo"),new Vertex("Metroville"));
    graph.addEdge(new Vertex("Naboo"),new Vertex("Monstroplolis"));
    graph.addEdge(new Vertex("Narnia"),new Vertex("Naboo"));
        String[]expectedArraay={"Pandora", "Arendelle", "Metroville", "Monstroplolis", "Naboo", "Narnia"};



assertEquals(Arrays.toString(expectedArraay),graph.DepthFirst(new Vertex("Pandora")).toString());
    }



    @Test void test2() {
        Graph graph=new Graph();
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("G");
        graph.addNode("D");
        graph.addNode("E");
        graph.addNode("H");
        graph.addNode("F");

        graph.addEdge(new Vertex("A"),new Vertex("B"));
        graph.addEdge(new Vertex("B"),new Vertex("C"));

        graph.addEdge(new Vertex("C"),new Vertex("G"));
        graph.addEdge(new Vertex("A"),new Vertex("D"));
        graph.addEdge(new Vertex("B"),new Vertex("D"));
        graph.addEdge(new Vertex("D"),new Vertex("E"));
        graph.addEdge(new Vertex("D"),new Vertex("H"));
        graph.addEdge(new Vertex("D"),new Vertex("F"));


        graph.addEdge(new Vertex("F"),new Vertex("H"));
        graph.addEdge(new Vertex("D"),new Vertex("B"));

        ArrayList<String> result = graph.DepthFirst(new Vertex("A"));
        ArrayList<String> expected = new  ArrayList<String>();
        expected.add("A");
        expected.add("B");
        expected.add("C");
        expected.add("G");
        expected.add("D");

        expected.add("E");
        expected.add("H");
        expected.add("F");

        assertEquals(expected,result);
    }


    @Test void test3() {
        Graph graph=new Graph();
        graph.addNode("one");
        graph.addNode("two");
        graph.addNode("three");
        graph.addNode("fore");
        graph.addNode("5");
        graph.addNode("6");

        graph.addEdge(new Vertex("one"),new Vertex("two"));
        graph.addEdge(new Vertex("two"),new Vertex("three"));
        graph.addEdge(new Vertex("three"),new Vertex("fore"));
        graph.addEdge(new Vertex("fore"),new Vertex("5"));
        graph.addEdge(new Vertex("fore"),new Vertex("6"));
        graph.addEdge(new Vertex("6"),new Vertex("one"));

        String[]expectedArraay={"one", "two", "three", "fore", "5", "6"};



       assertEquals(Arrays.toString(expectedArraay),graph.DepthFirst(new Vertex("one")).toString());
    }
}
