/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ReciprocalFactorial;
import java.math.*;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {



        System.out.println(ReciprocalFactorial(10));
    }
    static BigDecimal  ReciprocalFactorial(int num){
        BigDecimal factorial = BigDecimal.ONE;
        BigDecimal resulus = BigDecimal.ZERO;
        BigDecimal div= BigDecimal.ONE;

        for(int i = 2; i <= num; ++i)
        {
            // I!
            factorial = factorial.multiply(BigDecimal.valueOf(i));
            //div=1/I!
            div = BigDecimal.ONE.divide(factorial,15,RoundingMode.CEILING);

            resulus= resulus.add(div);

        }
        return resulus;
    }


}
