/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeatedWord;

import java.util.HashMap;
import java.util.Locale;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        System.out.println(repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only..."));
    }

    public static String repeatedWord(String input) {
        input = input.toLowerCase(Locale.ROOT);
        input = input.replace(",", "");
        HashMap<String, Integer> COUNTER = new HashMap<>();
        String[] words = input.split(" ");


        for (int i = 0; i < words.length; i++) {
            COUNTER.computeIfPresent(words[i], (k, v) -> v + 1);
            COUNTER.computeIfAbsent(words[i], s -> 1);

            if (COUNTER.get(words[i]) > 1) {
                System.out.println(COUNTER.get(words[i])
                        + words[i] + i);
                return words[i];
            }


        }


        return null;
    }
}

