/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void push() {
        Node newNode=new Node("wael");
        Node newNode2=new Node("yazan");
        Node newNode3=new Node("ahamd");
        Queue QQ=new Queue();
        QQ.enqueue(newNode);
        QQ.enqueue(newNode2);
        QQ.enqueue(newNode3);
        assertEquals(QQ.toString(),"Queue{ahamd <=yazan <=wael <=null}");// test push

    }


    @Test void pop() {
        Node newNode=new Node("wael");
        Node newNode2=new Node("yazan");
        Node newNode3=new Node("ahamd");
        Queue QQ=new Queue();
        QQ.enqueue(newNode);
        QQ.enqueue(newNode2);
        QQ.enqueue(newNode3);
              QQ.dequeue();//de
        assertEquals(QQ.toString(),"Queue{yazan <=wael <=null}");//test pop
    }
}
