/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package illegalCharacter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Sanitizer("http://code.org/hour of code.html");
    }


public static String Sanitizer(String url)
{
String[]urlArr= url.split("");
    for (int i = 0; i < urlArr.length; i++) {
        if(urlArr[i].equals(" ")){
            urlArr[i]="%20" ;
        }

    }
return String.join("",urlArr);
}
}
