/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.breadth.first;

import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Set;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Graph graph=new Graph();



        graph.addNode("Pandora");
        graph.addNode("Arendelle");
         graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
         graph.addNode("Narnia");
        graph.addNode("Naboo");

        graph.addEdge(new Vertex("Pandora"),new Vertex("Arendelle"));
        graph.addEdge(new Vertex("Metroville"),new Vertex("Arendelle"));
        graph.addEdge(new Vertex("Monstroplolis"),new Vertex("Arendelle"));
        graph.addEdge(new Vertex("Monstroplolis"),new Vertex("Metroville"));
        graph.addEdge(new Vertex("Metroville"),new Vertex("Narnia"));

        graph.addEdge(new Vertex("Naboo"),new Vertex("Metroville"));
        graph.addEdge(new Vertex("Naboo"),new Vertex("Monstroplolis"));
        graph.addEdge(new Vertex("Narnia"),new Vertex("Naboo"));

graph.DepthFirst(new Vertex("Pandora"));


    }



}
