/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.brackets;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        assertEquals(validation.validatebrackets("{}(){}"), true);
        assertEquals(validation.validatebrackets("()[[Extra Characters]]"), true);
        assertEquals(validation.validatebrackets("(){}[[]]"), true);
        assertEquals(validation.validatebrackets("{}{Code}[Fellows](())"), true);

        assertEquals(validation.validatebrackets("[({}]"), false);
        assertEquals(validation.validatebrackets("(]("), false);
        assertEquals(validation.validatebrackets("{(})"), false);
        assertEquals(validation.validatebrackets("{)"), false);

        assertEquals(validation.validatebrackets("{"), false);
        assertEquals(validation.validatebrackets("("), false);

        assertEquals(validation.validatebrackets("{)"), false);

    }
}
