/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.brackets;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }





    public static void main(String[] args) {
         System.out.println(validation.validatebrackets("][[[][]]898]"));
          System.out.println(validation.validatebrackets("][[[][]]898]"));
           System.out.println(validation.validatebrackets("][[[][]]898]"));
            System.out.println(validation.validatebrackets("][[[][]]898]"));
      System.out.println(validation.validatebrackets("][[[][]]]"));
        System.out.println(validation.validatebrackets("][[[][]]{]"));
        System.out.println(validation.validatebrackets("][[[][]]898]"));
    }
}
