/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.fizz.buzz;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test() {

        Node newNode= new Node(3);
        kArrTree tree = new kArrTree(newNode);
        tree.getRoot().addChild(5);
        tree.getRoot().addChild(15);
        // Add child node [2,1,6] in node (8)
        tree.getRoot().getChild().get(0).addChild(8);
        ArrayList test=new ArrayList<>();
        test.add("Fizz");
        test.add("Buzz");
        test.add("8");
        test.add("FizzBuzz");
        assertEquals(App.FizzBuzz(tree).print(),test);
    }
}
