/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeftJoin;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        HashMap<String,String> hash1= new HashMap<String,String>();
        hash1.put("wael","waed");
        hash1.put("khallel","yazan");
        hash1.put("ali","omar");
        hash1.put("majed","hazim");




        HashMap<String,String> hash2= new HashMap<String,String>();
        //  hash1.put("wael","waed");
        hash2.put("khallel","1");
        hash2.put("I","omar");
        hash2.put("majed","2");
        System.out.println(leftJoin(hash1,hash2));


    }


    public static List<List<String>> leftJoin(HashMap<String,String> left,HashMap<String,String> right){
        List<List<String>> returned= new ArrayList<>();
        for (String key:left.keySet()) {
            String[]arr=new String[3];
            arr[0]=key;
            arr[1]=left.get(key);
            arr[2]=right.get(key);
            returned.add(Arrays.asList( arr));

        }
        return returned;
    }

}
