/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.insertions;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @DisplayName("Append one  value test")
    @Test void appendOneTest() {

        linkedList<String> classUnderTest = new linkedList<>();
        classUnderTest.append("wael");
        assertEquals(classUnderTest.gitNode(),"wael=>null");// test 1

    }



    @DisplayName("Append  multi value test")
    @Test void addendTest() {

        linkedList<String> classUnderTest3 = new linkedList<>();
        classUnderTest3.append("wael");
           classUnderTest3.append("ahmad");
        classUnderTest3.append("yazan");
        assertEquals(classUnderTest3.gitNode(),"wael=>ahmad=>yazan=>null"); //test2

    }


    @DisplayName("Add before middle value test")
    @Test void addBefoorTest() {

        linkedList<String> classUnderTest2 = new linkedList<>();
        classUnderTest2.append("first");// 1
        classUnderTest2.append("middle");// middil
        classUnderTest2.append("finale");//3

        classUnderTest2.insertBefor("middle","VALUE");

        assertEquals(classUnderTest2.gitNode(),"first=>VALUE=>middle=>finale=>null"); //test2

    }



    @DisplayName("add before first value test")
    @Test void addBefooFirstTest() {

        linkedList<String> classUnderTest5 = new linkedList<>();
        classUnderTest5.append("first");// 1
        classUnderTest5.append("middle");// middil
        classUnderTest5.append("finale");//3

        classUnderTest5.insertBefor("first","VALUE");

        assertEquals(classUnderTest5.gitNode(),"VALUE=>first=>middle=>finale=>null"); //test2

    }


    @DisplayName("add After middle value test")
    @Test void addAfterMiddleTest() {

        linkedList<String> classUnderTest5 = new linkedList<>();
        classUnderTest5.append("first");// 1
        classUnderTest5.append("middle");// middil
        classUnderTest5.append("finale");//3

        classUnderTest5.insertAfter("middle","VALUE");// add

        assertEquals(classUnderTest5.gitNode(),"first=>middle=>VALUE=>finale=>null"); //test2

    }



    @DisplayName("add after finale value test")
    @Test void addAfterFinalTest() {

        linkedList<String> classUnderTest5 = new linkedList<>();
        classUnderTest5.append("first");// 1
        classUnderTest5.append("middle");// middil
        classUnderTest5.append("finale");//3

        classUnderTest5.insertAfter("finale","VALUE");// add

        assertEquals(classUnderTest5.gitNode(),"first=>middle=>finale=>VALUE=>null"); //test2

    }


}
