/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.kth;

public class Library {
    public static void main(String[] args) {
        linkedList<Integer> Nodes=new linkedList<>();
        Nodes.add(2);
        Nodes.add(8);
        Nodes.add(3);
        Nodes.add(1);




       System.out.println(Nodes.toString());
        System.out.println( Nodes.kthFromEnd(2));

    }
}
